In [38]:
import sys
import numpy 
import pandas 
import matplotlib
import seaborn 
import scipy
import sklearn 

print('Python: {}'.format(sys.version))
print('Numpy: {}'.format(numpy.__version__))
print('Pandas: {}'.format(pandas.__version__))
print('Matplotlib: {}'.format(matplotlib.__version__))
print('Seaborn: {}'.format(seaborn.__version__))
print('Scipy: {}'.format(scipy.__version__))
print('Sklearn: {}'.format(sklearn.__version__))

Python: 3.8.0 (v3.8.0:fa919fdf25, Oct 14 2019, 10:23:27)
[Clang 6.0 (clang-600.0.57)]
Numpy: 1.17.4
Pandas: 0.25.3
Matplotlib: 3.1.2
Seaborn: 0.11.1
Scipy: 1.3.3
Sklearn: 0.22

In [39]:
data = pd.read_csv('Police_Data.csv')

In [40]:
data

,stop_date,stop_time,country_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,1/2/2005,1:55,NaN,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
1,1/18/2005,8:15,NaN,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
2,1/23/2005,23:15,NaN,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
3,2/20/2005,17:15,NaN,M,1986.0,19.0,White,Call for Service,Other,False,NaN,Arrest Driver,True,16-30 Min,False
4,3/14/2005,10:00,NaN,F,1984.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65530,12/6/2012,17:54,NaN,F,1987.0,25.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
65531,12/6/2012,22:22,NaN,M,1954.0,58.0,White,Speeding,Speeding,False,NaN,Warning,False,0-15 Min,False
65532,12/6/2012,23:20,NaN,M,1985.0,27.0,Black,Equipment/Inspection Violation,Equipment,False,NaN,Citation,False,0-15 Min,False
65533,12/7/2012,0:23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,False
65534,12/7/2012,0:30,NaN,F,1985.0,27.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False

In [41]:
data.head

<bound method NDFrame.head of        stop_date stop_time  country_name driver_gender  driver_age_raw  \
0       1/2/2005      1:55           NaN             M          1985.0
1      1/18/2005      8:15           NaN             M          1965.0
2      1/23/2005     23:15           NaN             M          1972.0
3      2/20/2005     17:15           NaN             M          1986.0
4      3/14/2005     10:00           NaN             F          1984.0
...          ...       ...           ...           ...             ...
65530  12/6/2012     17:54           NaN             F          1987.0
65531  12/6/2012     22:22           NaN             M          1954.0
65532  12/6/2012     23:20           NaN             M          1985.0
65533  12/7/2012      0:23           NaN           NaN             NaN
65534  12/7/2012      0:30           NaN             F          1985.0

       driver_age driver_race                   violation_raw  violation  \
0            20.0       White                        Speeding   Speeding
1            40.0       White                        Speeding   Speeding
2            33.0       White                        Speeding   Speeding
3            19.0       White                Call for Service      Other
4            21.0       White                        Speeding   Speeding
...           ...         ...                             ...        ...
65530        25.0       White                        Speeding   Speeding
65531        58.0       White                        Speeding   Speeding
65532        27.0       Black  Equipment/Inspection Violation  Equipment
65533         NaN         NaN                             NaN        NaN
65534        27.0       White                        Speeding   Speeding

       search_conducted search_type   stop_outcome is_arrested stop_duration  \
0                 False         NaN       Citation       False      0-15 Min
1                 False         NaN       Citation       False      0-15 Min
2                 False         NaN       Citation       False      0-15 Min
3                 False         NaN  Arrest Driver        True     16-30 Min
4                 False         NaN       Citation       False      0-15 Min
...                 ...         ...            ...         ...           ...
65530             False         NaN       Citation       False      0-15 Min
65531             False         NaN        Warning       False      0-15 Min
65532             False         NaN       Citation       False      0-15 Min
65533             False         NaN            NaN         NaN           NaN
65534             False         NaN       Citation       False      0-15 Min

       drugs_related_stop
0                   False
1                   False
2                   False
3                   False
4                   False
...                   ...
65530               False
65531               False
65532               False
65533               False
65534               False

[65535 rows x 15 columns]>

In [42]:
print(data.columns)

Index(['stop_date', 'stop_time', 'country_name', 'driver_gender',
       'driver_age_raw', 'driver_age', 'driver_race', 'violation_raw',
       'violation', 'search_conducted', 'search_type', 'stop_outcome',
       'is_arrested', 'stop_duration', 'drugs_related_stop'],
      dtype='object')

In [43]:
print(data.shape)

(65535, 15)

In [44]:
data.describe()

       country_name  driver_age_raw    driver_age
count           0.0    61481.000000  61228.000000
mean            NaN     1967.791106     34.148984
std             NaN      121.050106     12.760710
min             NaN        0.000000     15.000000
25%             NaN     1965.000000     23.000000
50%             NaN     1978.000000     31.000000
75%             NaN     1985.000000     43.000000
max             NaN     8801.000000     88.000000